# Generated by Django 4.2.7 on 2024-03-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_items_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300, unique=True)),
                ('purchase_price', models.IntegerField()),
                ('items_sale_price', models.IntegerField()),
                ('item_sold', models.IntegerField(default=0)),
                ('items_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Irumudi_bookig_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('cust_name', models.CharField(max_length=100)),
                ('irumudi_price', models.IntegerField()),
                ('irumudi_qty', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('sch_date', models.DateField()),
                ('paid_amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
