# Generated by Django 4.2.7 on 2024-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irumudi_bookig_receipt',
            name='receipt_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
