# Generated by Django 4.2.7 on 2024-03-22 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_sold_rcpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Booking_Date', models.DateField(default=datetime.date.today)),
                ('Product_name', models.TextField()),
                ('Total_Amount', models.IntegerField()),
            ],
        ),
    ]
