# Generated by Django 4.2.7 on 2024-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irumudi_bookig_receipt',
            name='Total_Amount',
            field=models.IntegerField(),
        ),
    ]
