# Generated by Django 5.0.3 on 2024-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_alter_irumudi_bookig_receipt_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='irumudi_bookig_receipt',
            name='Balance_Amount_Payment_Mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
