# Generated by Django 4.2.7 on 2024-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_alter_irumudi_bookig_receipt_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irumudi_bookig_receipt',
            name='Balance_Clear_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
