# Generated by Django 5.0.3 on 2024-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_irumudi_bookig_receipt_balance_amount_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='Cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donations',
            name='UPI',
            field=models.IntegerField(default=0),
        ),
    ]
