# Generated by Django 4.2.7 on 2024-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_alter_irumudi_bookig_receipt_balance_clear_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghee_coconut',
            name='Cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ghee_coconut',
            name='UPI',
            field=models.IntegerField(default=0),
        ),
    ]
