# Generated by Django 4.2.7 on 2024-03-27 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_rename_booking_date_items_sold_rcpt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Description', models.TextField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
