# Generated by Django 4.2.7 on 2024-03-29 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Income', models.IntegerField()),
            ],
        ),
    ]
