# Generated by Django 4.2.7 on 2024-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_ghee_coconut_cash_ghee_coconut_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_sold_rcpt',
            name='Cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items_sold_rcpt',
            name='UPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maaladharane',
            name='Cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maaladharane',
            name='UPI',
            field=models.IntegerField(default=0),
        ),
    ]
