# Generated by Django 5.0.3 on 2024-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_donations_cash_donations_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irumudi_bookig_receipt',
            name='Irumudi_Price',
            field=models.IntegerField(default=380),
        ),
    ]
