# Generated by Django 4.2.7 on 2024-03-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_rename_balance_irumudi_bookig_receipt_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Contact_id',
            new_name='Amount_Paid',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Date_created',
            new_name='Booking_Date',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Irumudi_price',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Cust_name',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Irumudi_qty',
            new_name='Irumudi_Price',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Paid_amount',
            new_name='Irumudi_Quantity',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Receipt_number',
            new_name='Receipt_Number',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Schedule_date',
            new_name='Schedule_Date',
        ),
        migrations.RenameField(
            model_name='irumudi_bookig_receipt',
            old_name='Total_amount',
            new_name='Total_Amount',
        ),
    ]
