# Generated by Django 4.2.7 on 2024-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0005_rename_contact_id_irumudi_bookig_receipt_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irumudi_bookig_receipt',
            name='Contact',
            field=models.TextField(),
        ),
    ]
