# Generated by Django 4.2.7 on 2024-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0005_daily_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_expense',
            name='Income',
            field=models.IntegerField(default=0),
        ),
    ]
