# Generated by Django 4.2.7 on 2024-04-01 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0006_alter_daily_expense_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Contact', models.TextField()),
                ('Amount_Paid', models.IntegerField()),
            ],
        ),
    ]
